// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKx5jnoA3153Yv5y1I421d45d1Fm0fBI8',
    appId: '1:275702468748:web:d44efd1170aac891fbaba9',
    messagingSenderId: '275702468748',
    projectId: 'srocksmusic-homepage',
    authDomain: 'srocksmusic-homepage.firebaseapp.com',
    storageBucket: 'srocksmusic-homepage.firebasestorage.app',
    measurementId: 'G-JQSFBCB565',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRvtk6wzuoQ7Dee7p55cJO3tkBd6uSfVY',
    appId: '1:275702468748:android:917443fc9a05a619fbaba9',
    messagingSenderId: '275702468748',
    projectId: 'srocksmusic-homepage',
    storageBucket: 'srocksmusic-homepage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjclFvDp0QDsocw7digQJRMxmniMhOZ0g',
    appId: '1:275702468748:ios:d48ac3bccd4d15f3fbaba9',
    messagingSenderId: '275702468748',
    projectId: 'srocksmusic-homepage',
    storageBucket: 'srocksmusic-homepage.firebasestorage.app',
    iosBundleId: 'com.example.srocksAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjclFvDp0QDsocw7digQJRMxmniMhOZ0g',
    appId: '1:275702468748:ios:d48ac3bccd4d15f3fbaba9',
    messagingSenderId: '275702468748',
    projectId: 'srocksmusic-homepage',
    storageBucket: 'srocksmusic-homepage.firebasestorage.app',
    iosBundleId: 'com.example.srocksAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKx5jnoA3153Yv5y1I421d45d1Fm0fBI8',
    appId: '1:275702468748:web:b68b19ba08632399fbaba9',
    messagingSenderId: '275702468748',
    projectId: 'srocksmusic-homepage',
    authDomain: 'srocksmusic-homepage.firebaseapp.com',
    storageBucket: 'srocksmusic-homepage.firebasestorage.app',
    measurementId: 'G-6MN0VZ4PCG',
  );
}
